services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: clean-database
    ports:
      - "3306:3306"
    security_opt:
      - "no-new-privileges"